title: BStone
description: "Unofficial source port of Blake Stone: Aliens of Gold and Blake Stone: Planet Strike"
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
