cmake_minimum_required(VERSION 3.24.0 FATAL_ERROR)
project(bstone_lib_openal_soft VERSION 1.0.0 LANGUAGES NONE)
message(STATUS "[${PROJECT_NAME}] v${PROJECT_VERSION}")
add_library(${PROJECT_NAME} INTERFACE)
add_library(bstone::lib::openal_soft ALIAS ${PROJECT_NAME})
target_include_directories(${PROJECT_NAME} INTERFACE include/AL)
